### ISSUE TITLE
Looping error after siren (solo)

### ISSUE THREAD

**Issue by AdeptSephiel** [sharkster91/ExpandedHelicopterEvents#40]
First helicopter event (dropping flyers everywhere) went without issues.

On day 06/07 siren went off and then the following error started looping constantly:

Log:

STACK TRACE
-----------------------------------------
Callframe at: getTexture
function: setOrUpdate -- file: ExpandedHelicopter11_EventMarkerHandler.lua line # 52
function: unlaunch -- file: ExpandedHelicopter01c_MainCore.lua line # 749
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 204
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 283

LOG  : General     , 1642284924179> - EHE: OUT OF BOUNDS: HELI: HELI 1 (air_raid) [goHome] (x:8425, y:6421)
LOG  : General     , 1642284924179>  ---- UN-LAUNCH: HELI 1 (air_raid) [goHome] (x:8425, y:6421) day:6 hour:11
LOG  : General     , 1642284924180>  - EHE: stopAllHeldEventSounds for HELI 1 (air_raid) [goHome]
ERROR: General     , 1642284924180> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException:  at MethodArguments.assertValid line:123.
ERROR: General     , 1642284924180> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: 
	at se.krka.kahlua.integration.expose.MethodArguments.assertValid(MethodArguments.java:123)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:186)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
	at zombie.gameStates.IngameState.update(IngameState.java:1367)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:289)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:745)
	at zombie.GameWindow.run_ez(GameWindow.java:661)
	at zombie.GameWindow.mainThread(GameWindow.java:475)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1642284924180> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: getTexture
function: setOrUpdate -- file: ExpandedHelicopter11_EventMarkerHandler.lua line # 52
function: unlaunch -- file: ExpandedHelicopter01c_MainCore.lua line # 749
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 204
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 283

LOG  : General     , 1642284924188> - EHE: OUT OF BOUNDS: HELI: HELI 1 (air_raid) [goHome] (x:8424, y:6421)
LOG  : General     , 1642284924188>  ---- UN-LAUNCH: HELI 1 (air_raid) [goHome] (x:8424, y:6421) day:6 hour:11
LOG  : General     , 1642284924188>  - EHE: stopAllHeldEventSounds for HELI 1 (air_raid) [goHome]
ERROR: General     , 1642284924189> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException:  at MethodArguments.assertValid line:123.
ERROR: General     , 1642284924189> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: 
	at se.krka.kahlua.integration.expose.MethodArguments.assertValid(MethodArguments.java:123)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:186)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
	at zombie.gameStates.IngameState.update(IngameState.java:1367)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:289)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:745)
	at zombie.GameWindow.run_ez(GameWindow.java:661)
	at zombie.GameWindow.mainThread(GameWindow.java:475)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1642284924189> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: getTexture
function: setOrUpdate -- file: ExpandedHelicopter11_EventMarkerHandler.lua line # 52
function: unlaunch -- file: ExpandedHelicopter01c_MainCore.lua line # 749
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 204
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 283

LOG  : General     , 1642284924197> - EHE: OUT OF BOUNDS: HELI: HELI 1 (air_raid) [goHome] (x:8423, y:6421)
LOG  : General     , 1642284924197>  ---- UN-LAUNCH: HELI 1 (air_raid) [goHome] (x:8423, y:6421) day:6 hour:11
LOG  : General     , 1642284924197>  - EHE: stopAllHeldEventSounds for HELI 1 (air_raid) [goHome]
ERROR: General     , 1642284924197> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException:  at MethodArguments.assertValid line:123.
ERROR: General     , 1642284924197> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: 
	at se.krka.kahlua.integration.expose.MethodArguments.assertValid(MethodArguments.java:123)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:186)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
	at zombie.gameStates.IngameState.update(IngameState.java:1367)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:289)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:745)
	at zombie.GameWindow.run_ez(GameWindow.java:661)
	at zombie.GameWindow.mainThread(GameWindow.java:475)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1642284924198> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: getTexture
function: setOrUpdate -- file: ExpandedHelicopter11_EventMarkerHandler.lua line # 52
function: unlaunch -- file: ExpandedHelicopter01c_MainCore.lua line # 749
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 204
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 283

LOG  : General     , 1642284924204> EXITDEBUG: ToggleEscapeMenu 1
LOG  : General     , 1642284924204> EXITDEBUG: ToggleEscapeMenu 3
LOG  : General     , 1642284924204> EXITDEBUG: ToggleEscapeMenu 4
LOG  : General     , 1642284924205> EXITDEBUG: ToggleEscapeMenu 5
LOG  : General     , 1642284924205> EXITDEBUG: setGameSpeed 1
LOG  : General     , 1642284924205> EXITDEBUG: setGameSpeed 3
LOG  : General     , 1642284924205> EXITDEBUG: setShowPausedMessage 1
LOG  : General     , 1642284924205> EXITDEBUG: setShowPausedMessage 2
LOG  : General     , 1642284924205> ECC: OnKeyPressed ShandaLuna
LOG  : General     , 1642284924205> ECC-FILESYSTEM: expected-SP:Sandbox read absPath: config\ExpandedHelicopterEvents.config
LOG  : General     , 1642284924206> Easy-Config-Chucked: loading: modId: ExpandedHelicopterEvents

**Comment by ChuckTheSheep** [comment]
Thank you these help!

**Comment by ChuckTheSheep** [comment]
Please confirm if this occurs after today's update.

**Comment by AdeptSephiel** [comment]
Thank you! Seems to not be happening anymore after the update, but I'll keep an eye out.
