### ISSUE TITLE
Exceptions when starting dedicated server

### ISSUE THREAD

**Issue by UsernameIsToLon** [sharkster91/ExpandedHelicopterEvents#46]
```
LOG  : Lua         , 1642850839650> 784.218.525> Loading: C:/Users/User/Zomboid/Server/servertest_SandboxVars.lua
ERROR: General     , 1642850839698> 784.218.573> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Expected a table at KahluaUtil.fail line:82.
ERROR: General     , 1642850839701> 784.218.576> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Expected a table
        at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
        at se.krka.kahlua.vm.KahluaUtil.luaAssert(KahluaUtil.java:70)
        at se.krka.kahlua.stdlib.TableLib.pairs(TableLib.java:119)
        at se.krka.kahlua.stdlib.TableLib.call(TableLib.java:95)
        at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
        at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
        at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
        at zombie.Lua.Event.trigger(Event.java:64)
        at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:61)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1384)
        at zombie.network.GameServer.main(GameServer.java:668)
LOG  : General     , 1642850839711> 784.218.586> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: table.pairs
function: setDictionary -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 46

ERROR: General     , 1642850839712> 784.218.586> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Expected a table at KahluaUtil.fail line:82.
ERROR: General     , 1642850839712> 784.218.587> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Expected a table
        at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
        at se.krka.kahlua.vm.KahluaUtil.luaAssert(KahluaUtil.java:70)
        at se.krka.kahlua.stdlib.TableLib.pairs(TableLib.java:119)
        at se.krka.kahlua.stdlib.TableLib.call(TableLib.java:95)
        at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
        at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
        at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
        at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
        at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
        at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
        at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
        at zombie.Lua.Event.trigger(Event.java:64)
        at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:61)
        at zombie.network.GameServer.doMinimumInit(GameServer.java:1384)
        at zombie.network.GameServer.main(GameServer.java:668)
LOG  : General     , 1642850839720> 784.218.594> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: table.pairs
function: loadAnnouncersToConfig -- file: ExpandedHelicopter09_EasyConfigOptions.lua line # 29
function: sandboxOptionsEnd -- file: ExpandedHelicopter09_EasyConfigOptions.lua line # 57

LOG  : General     , 1642850839720> 784.218.595> EHE: Disabling vanilla helicopter. Adding items to WorldItemRemovalList.
LOG  : Lua         , 1642850839731> 784.218.605> Loading: C:/Users/User/Zomboid/Server/servertest_spawnregions.lua
```

Complete console.log: https://pastebin.com/VXh3NUqa

**Comment by ChuckTheSheep** [comment]
This should be fixed by updates from 3 days ago. Open another ticket if it occurs again.
