### ISSUE TITLE
A server that has been in the world for two months

### ISSUE THREAD

**Issue by wyh1346** [sharkster91/ExpandedHelicopterEvents#48]
Can't seen any helicopters yet，After restarting and joining the game, see the following prompt in the background

LOG  : General     , 1642951514326> 110,176,531> Missing texture: media/textures/weather/fogwhite.png
LOG  : General     , 1642951514362> 110,176,567> -------------------------------------------------------------
attempted index: flightHours of non-table: null

LOG  : General     , 1642951514436> 110,176,642> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291

ERROR: General     , 1642951514440> 110,176,645> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: flightHours of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1642951514441> 110,176,646> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: flightHours of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
	at zombie.gameStates.IngameState.update(IngameState.java:1367)
	at zombie.network.GameServer.main(GameServer.java:890)
LOG  : General     , 1642951514443> 110,176,649> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291

LOG  : General     , 1642951515169> 110,177,375> Item -> Radio item = Radio.CDplayer
LOG  : General     , 1642951515204> 110,177,410> Warning: Radio worldsprite not valid, sprite = 
LOG  : General     , 1642951515206> 110,177,412> Moveable.load -> Radio item = Radio.CDplayer
LOG  : General     , 1642951516260> 110,178,465> Item -> Radio item = Radio.CDplayer
LOG  : General     , 1642951516331> 110,178,537> Warning: Radio worldsprite not valid, sprite = 
LOG  : General     , 1642951516367> 110,178,572> Moveable.load -> Radio item = Radio.CDplayer
LOG  : General     , 1642951520631> 110,182,837> CZServer - GetServerConfigs: Sent server configs to client --> yongqi
LOG  : General     , 1642951581746> 110,243,949> -------------------------------------------------------------
attempted index: flightHours of non-table: null

LOG  : General     , 1642951581748> 110,243,951> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291

ERROR: General     , 1642951581749> 110,243,953> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: flightHours of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1642951581751> 110,243,954> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: flightHours of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
	at zombie.gameStates.IngameState.update(IngameState.java:1367)
	at zombie.network.GameServer.main(GameServer.java:890)
LOG  : General     , 1642951581753> 110,243,956> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291

LOG  : General     , 1642951732116> 110,394,316> -------------------------------------------------------------
attempted index: flightHours of non-table: null

LOG  : General     , 1642951732116> 110,394,316> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291

ERROR: General     , 1642951732118> 110,394,318> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: flightHours of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1642951732118> 110,394,318> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: flightHours of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
	at zombie.gameStates.IngameState.update(IngameState.java:1367)
	at zombie.network.GameServer.main(GameServer.java:890)
LOG  : General     , 1642951732120> 110,394,321> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291

LOG  : General     , 1642951882309> 110,544,508> -------------------------------------------------------------
attempted index: flightHours of non-table: null

LOG  : General     , 1642951882313> 110,544,511> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291

ERROR: General     , 1642951882314> 110,544,512> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: flightHours of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1642951882315> 110,544,513> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: flightHours of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:88)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1673)
	at zombie.gameStates.IngameState.update(IngameState.java:1367)
	at zombie.network.GameServer.main(GameServer.java:890)
LOG  : General     , 1642951882316> 110,544,514> -----------------------------------------
STACK TRACE
-----------------------------------------
function: eHeliEvent_ScheduleNew -- file: ExpandedHelicopter06_EventScheduler.lua line # 157
function: eHeliEvent_OnHour -- file: ExpandedHelicopter06_EventScheduler.lua line # 291
[server-console.txt](https://github.com/sharkster91/ExpandedHelicopterEvents/files/7920772/server-console.txt)

**Comment by ChuckTheSheep** [comment]
This should be fixed by the latest update. Please confirm this error is still occurring with the line `Expanded Helicopter Events: ver:` ending with `0.3.6-HOTFIX-SchedulerMP`. This would be found in `console.txt` and `coop-console.txt`.

**Comment by ChuckTheSheep** [comment]
Closing to defer to newer issue reported.
