### ISSUE TITLE
No Heli icon, no sound, very laggy and no helicrash

### ISSUE THREAD

**Issue by ZSHADOWWOLF** [sharkster91/ExpandedHelicopterEvents#73]
Today in my server i get this errors stable, can't see heli icon, but found crash or heli by Sound Direction Indicator mod. Looks like about crash, and huge horde, but in epicenter no helicrash, no parts, no metal bars or resources, only horde and game freezes, in forests. 

ERROR: General     , 1661687674553> 561,154,815> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: DistTo of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1661687674553> 561,154,815> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: DistTo of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1664)
	at zombie.gameStates.IngameState.update(IngameState.java:1373)
	at zombie.network.GameServer.main(GameServer.java:920)
LOG  : General     , 1661687674553> 561,154,815> -----------------------------------------
STACK TRACE
-----------------------------------------
function: lookForHostiles -- file: ExpandedHelicopter04_Attack.lua line # 24 | MOD: Expanded Helicopter Events
function: updateSubFunctions -- file: ExpandedHelicopter01e_MainUpdate.lua line # 282 | MOD: Expanded Helicopter Events
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 206 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 297 | MOD: Expanded Helicopter Events

LOG  : General     , 1661687674752> 561,155,014> -------------------------------------------------------------
attempted index: DistTo of non-table: null

LOG  : General     , 1661687674752> 561,155,014> -----------------------------------------
STACK TRACE
-----------------------------------------
function: lookForHostiles -- file: ExpandedHelicopter04_Attack.lua line # 24 | MOD: Expanded Helicopter Events
function: updateSubFunctions -- file: ExpandedHelicopter01e_MainUpdate.lua line # 282 | MOD: Expanded Helicopter Events
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 206 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 297 | MOD: Expanded Helicopter Events

ERROR: General     , 1661687674752> 561,155,015> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: DistTo of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1661687674752> 561,155,015> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: DistTo of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1664)
	at zombie.gameStates.IngameState.update(IngameState.java:1373)
	at zombie.network.GameServer.main(GameServer.java:920)
LOG  : General     , 1661687674753> 561,155,015> -----------------------------------------
STACK TRACE
-----------------------------------------
function: lookForHostiles -- file: ExpandedHelicopter04_Attack.lua line # 24 | MOD: Expanded Helicopter Events
function: updateSubFunctions -- file: ExpandedHelicopter01e_MainUpdate.lua line # 282 | MOD: Expanded Helicopter Events
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 206 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 297 | MOD: Expanded Helicopter Events

LOG  : General     , 1661687674950> 561,155,212> -------------------------------------------------------------
attempted index: DistTo of non-table: null

LOG  : General     , 1661687674950> 561,155,213> -----------------------------------------
STACK TRACE
-----------------------------------------
function: lookForHostiles -- file: ExpandedHelicopter04_Attack.lua line # 24 | MOD: Expanded Helicopter Events
function: updateSubFunctions -- file: ExpandedHelicopter01e_MainUpdate.lua line # 282 | MOD: Expanded Helicopter Events
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 206 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 297 | MOD: Expanded Helicopter Events

ERROR: General     , 1661687674950> 561,155,213> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: DistTo of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1661687674951> 561,155,213> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: DistTo of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:641)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1664)
	at zombie.gameStates.IngameState.update(IngameState.java:1373)
	at zombie.network.GameServer.main(GameServer.java:920)
LOG  : General     , 1661687674951> 561,155,213> -----------------------------------------
STACK TRACE
-----------------------------------------
function: lookForHostiles -- file: ExpandedHelicopter04_Attack.lua line # 24 | MOD: Expanded Helicopter Events
function: updateSubFunctions -- file: ExpandedHelicopter01e_MainUpdate.lua line # 282 | MOD: Expanded Helicopter Events
function: update -- file: ExpandedHelicopter01e_MainUpdate.lua line # 206 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 297 | MOD: Expanded Helicopter Events

**Comment by ChuckTheSheep** [comment]
Thank you.

**Comment by ChuckTheSheep** [comment]
82c0323249c183451533fb27eb6fc500f271648f
