### ISSUE TITLE
Exception thrown java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList at KahluaUtil.fail line:82

### ISSUE THREAD

**Issue by adamhilton** [sharkster91/ExpandedHelicopterEvents#75]
The update that went out on August 30th, 2022 seems to have caused all clients to experience the following error and causes the came to be unplayable while playing on a dedicated server:

> LOG  : General     , 1661910309029> 0> -----------------------------------------
> STACK TRACE
> -----------------------------------------
> function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 60 | MOD: Expanded Helicopter Events
> function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 226 | MOD: Expanded Helicopter Events
> 
> ERROR: General     , 1661910309029> 0> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList at KahluaUtil.fail line:82.
> ERROR: General     , 1661910309029> 0> DebugLogStream.printException> Stack trace:
> java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList
> 	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
> 	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
> 	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
> 	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
> 	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
> 	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
> 	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
> 	at zombie.Lua.Event.trigger(Event.java:64)
> 	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
> 	at zombie.iso.IsoChunk.doLoadGridsquare(IsoChunk.java:3329)
> 	at zombie.iso.IsoChunkMap.processAllLoadGridSquare(IsoChunkMap.java:155)
> 	at zombie.gameStates.IngameState.enter(IngameState.java:715)
> 	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:145)
> 	at zombie.GameWindow.logic(GameWindow.java:297)
> 	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
> 	at zombie.GameWindow.frameStep(GameWindow.java:764)
> 	at zombie.GameWindow.run_ez(GameWindow.java:680)
> 	at zombie.GameWindow.mainThread(GameWindow.java:494)
> 	at java.base/java.lang.Thread.run(Unknown Source)
> LOG  : General     , 1661910309029> 0> -----------------------------------------
> STACK TRACE
> -----------------------------------------

~~Issue does not appear to occur on locally hosted servers.~~
Update: Issue actually is reproducible hosting locally as well. 

Let me know if there is any additional info I can provide to help!

**Comment by Lefttroll** [comment]
Same problem!
[logs.zip](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9458421/logs.zip)
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 60 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 226 | MOD: Expanded Helicopter Events

ERROR: General     , 1661919663574> 126а677а888> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList at KahluaUtil.fail line:82.
ERROR: General     , 1661919663574> 126а677а888> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.iso.IsoChunk.doLoadGridsquare(IsoChunk.java:3329)
	at zombie.iso.IsoChunkMap.update(IsoChunkMap.java:199)
	at zombie.iso.IsoCell.updateInternal(IsoCell.java:5707)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoCell.update(IsoCell.java:5668)
	at zombie.iso.IsoWorld.updateInternal(IsoWorld.java:3479)
	at zombie.util.lambda.Invokers$Params1$CallbackStackItem.run(Invokers.java:37)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.lambda$invokeAndMeasure$0(AbstractPerformanceProfileProbe.java:83)
	at zombie.util.lambda.Stacks$Params3$CallbackStackItem.invoke(Stacks.java:230)
	at zombie.util.lambda.Stacks$GenericStack.invokeAndRelease(Stacks.java:26)
	at zombie.util.Lambda.capture(Lambda.java:130)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:81)
	at zombie.iso.IsoWorld.update(IsoWorld.java:3407)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1657)
	at zombie.gameStates.IngameState.update(IngameState.java:1373)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:297)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:764)
	at zombie.GameWindow.run_ez(GameWindow.java:666)
	at zombie.GameWindow.mainThread(GameWindow.java:494)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1661919663577> 126а677а890> -----------------------------------------

From sus mods i have i think
https://steamcommunity.com/sharedfiles/filedetails/?id=1178772929
can cause issues since it doesnt use standar zomboid server logic

**Comment by ChuckTheSheep** [comment]
Duplicate issue to #76 - should be fixed with AUG 31st patch.
