### ISSUE TITLE
[STABLE 41.73] Constant error spam that causes lag

### ISSUE THREAD

**Issue by Lefttroll** [sharkster91/ExpandedHelicopterEvents#76]
i've encountered this issue while playing on our server {104.243.37.9:16261} 
from logs it seems like game tries to create a spawnlist and it fails.
[logs.zip](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9458439/logs.zip)
STACK TRACE
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 60 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 226 | MOD: Expanded Helicopter Events

LOG  : General     , 1661919586674> 0> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 60 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 226 | MOD: Expanded Helicopter Events

ERROR: General     , 1661919586674> 0> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList at KahluaUtil.fail line:82.
ERROR: General     , 1661919586675> 0> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.iso.IsoChunk.doLoadGridsquare(IsoChunk.java:3329)
	at zombie.iso.IsoChunkMap.processAllLoadGridSquare(IsoChunkMap.java:155)
	at zombie.gameStates.IngameState.enter(IngameState.java:715)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:145)
	at zombie.GameWindow.logic(GameWindow.java:297)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:764)
	at zombie.GameWindow.run_ez(GameWindow.java:666)
	at zombie.GameWindow.mainThread(GameWindow.java:494)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1661919586678> 0> -----------------------------------------

i suspect that this mod maybe somehow connected to problem - https://steamcommunity.com/sharedfiles/filedetails/?id=1178772929
it asks you to replace standard zombie.network.GameServer with custom zombie.SSROverride.

**Comment by ChuckTheSheep** [comment]
Should have been fixed with the AUG 31st patch.
