### ISSUE TITLE
Server crashing when trying to load events

### ISSUE THREAD

**Issue by Lawlkitties** [sharkster91/ExpandedHelicopterEvents#82]
Hello, recently I've been getting a lot of server crashes when trying to play my first week on my new server. Right before crashing, the server will slow to a crawl and repeat this message in the console until it kicks the bucket. I'm no code doctor, but from what little I can parse this seems like some sort of mod-related issue related to accessing/loading a file related to events. If I have incorrectly configured the mod somehow, please let me know, otherwise, I'm sort of out of ideas.

LOG  : General     , 1664616281651> 7,414,265,394> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 60 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 227 | MOD: Expanded Helicopter Events
LOG  : General     , 1664616281651> 7,414,265,395> -----------------------------------------
STACK TRACE
-----------------------------------------
function: getOrSetPendingSpawnsList -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 60 | MOD: Expanded Helicopter Events
function: parseSquare -- file: ExpandedHelicopter00c_SpawnerAPI.lua line # 227 | MOD: Expanded Helicopter Events
ERROR: General     , 1664616281651> 7,414,265,395> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList at KahluaUtil.fail line:82.
ERROR: General     , 1664616281651> 7,414,265,395> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Object tried to call nil in getOrSetPendingSpawnsList
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.iso.IsoChunk.doLoadGridsquare(IsoChunk.java:3329)
	at zombie.network.ServerMap$ServerCell.RecalcAll2(ServerMap.java:304)
	at zombie.network.ServerMap$ServerCell.Load2(ServerMap.java:162)
	at zombie.network.ServerMap.preupdate(ServerMap.java:790)
	at zombie.network.GameServer.main(GameServer.java:892)

**Comment by ChuckTheSheep** [comment]
This should have been fixed with an earlier hotfix. Let me know if I am mistaken.
