### ISSUE TITLE
Constant player crashes, error spams logs

### ISSUE THREAD

**Issue by mjvej4f** [sharkster91/ExpandedHelicopterEvents#86]
It's been doing this even when there is no heli event, and it only lasts like a minute which might be random anyways and a feature intended but on my server, everytime a heli event passes, a player will crash and it spams my console with things like this nonstop until next restart

LOG  : General     , 1668044926813> 233,782,449> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@48153981
function: updatePos -- file: ExpandedHelicopter01b_MainSounds.lua line # 150 | MOD: Expanded Helicopter Events
function: updatePosition -- file: ExpandedHelicopter01c_MainCore.lua line # 265 | MOD: Expanded Helicopter Events
function: move -- file: ExpandedHelicopter01c_MainCore.lua line # 316 | MOD: Expanded Helicopter Events
function: updateEvent -- file: ExpandedHelicopter01e_MainUpdate.lua line # 181 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 278 | MOD: Expanded Helicopter Events

ERROR: General     , 1668044926814> 233,782,450> ExceptionLogger.logException> Exception thrown java.lang.reflect.InvocationTargetException at NativeMethodAccessorImpl.invoke0 (Native Method).
ERROR: General     , 1668044926815> 233,782,450> DebugLogStream.printException> Stack trace:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:60)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
	at zombie.gameStates.IngameState.update(IngameState.java:1333)
	at zombie.network.GameServer.main(GameServer.java:900)
Caused by: java.lang.IllegalStateException: can't call this function on the server
	at zombie.Lua.LuaManager$GlobalObject.sendClientCommand(LuaManager.java:5923)
	... 19 more
LOG  : General     , 1668044927012> 233,782,647> -----------------------------------------
STACK TRACE
-----------------------------------------
Callframe at: se.krka.kahlua.integration.expose.MultiLuaJavaInvoker@48153981
function: updatePos -- file: ExpandedHelicopter01b_MainSounds.lua line # 150 | MOD: Expanded Helicopter Events
function: updatePosition -- file: ExpandedHelicopter01c_MainCore.lua line # 265 | MOD: Expanded Helicopter Events
function: move -- file: ExpandedHelicopter01c_MainCore.lua line # 316 | MOD: Expanded Helicopter Events
function: updateEvent -- file: ExpandedHelicopter01e_MainUpdate.lua line # 181 | MOD: Expanded Helicopter Events
function: updateAllHelicopters -- file: ExpandedHelicopter01e_MainUpdate.lua line # 278 | MOD: Expanded Helicopter Events

ERROR: General     , 1668044927012> 233,782,648> ExceptionLogger.logException> Exception thrown java.lang.reflect.InvocationTargetException at NativeMethodAccessorImpl.invoke0 (Native Method).
ERROR: General     , 1668044927013> 233,782,649> DebugLogStream.printException> Stack trace:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at se.krka.kahlua.integration.expose.caller.MethodCaller.call(MethodCaller.java:62)
	at se.krka.kahlua.integration.expose.LuaJavaInvoker.call(LuaJavaInvoker.java:198)
	at se.krka.kahlua.integration.expose.MultiLuaJavaInvoker.call(MultiLuaJavaInvoker.java:60)
	at se.krka.kahlua.vm.KahluaThread.callJava(KahluaThread.java:182)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:1007)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:92)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1624)
	at zombie.gameStates.IngameState.update(IngameState.java:1333)
	at zombie.network.GameServer.main(GameServer.java:900)
Caused by: java.lang.IllegalStateException: can't call this function on the server
	at zombie.Lua.LuaManager$GlobalObject.sendClientCommand(LuaManager.java:5923)
	... 19 more
LOG  : General     , 1668044927211> 233,782,847> -----------------------------------------
STACK TRACE
-----------------------------------------

**Comment by mjvej4f** [comment]
[Serverlogs.zip](https://github.com/sharkster91/ExpandedHelicopterEvents/files/9977791/Serverlogs.zip)

**Comment by ChuckTheSheep** [comment]
This should have been fixed with 4d9a76332fb11042b0fe62c41ac6684b745ff5ef. Let me know if I am mistaken.
